classdef PlotManager < handle
% PlotManager: Small class that allows the same plots generated by some
% script to be either organized as subplots or single figures.
%
% Any openend figure using nextPlot can be exportet to a directory using a
% specified format.
%
% @author Daniel Wirtz @date 2012-04-12
%
% @new{0,6,dw,2012-04-12} Added this class.
%
% This class is part of the framework
% KerMor - Model Order Reduction using Kernels:
% - \c Homepage http://www.agh.ians.uni-stuttgart.de/research/software/kermor.html
% - \c Documentation http://www.agh.ians.uni-stuttgart.de/documentation/kermor/
% - \c License @ref licensing
    
    properties
        % Flag if single plots shall be used for subsequent calls to
        % nextPlot.
        %
        % @type logical @default true
        Single = true;
        
        % The figure size for each newly created figure when on single
        % mode.
        %
        % Is a two dimensional row vector with width and height
        %
        % @type rowvec<double> @default [600 480]
        SingleSize = [600 480];
        
        % A prefix that has to be put before each file name for exported
        % plots.
        %
        % @type char @default ''
        FilePrefix = '';
    end
    
    properties(Access=private)
        rows = 0;
        cols = 0;
    end
    
    properties(SetAccess=private, Transient)
        % Provides access to all handles (axes or figures) created using
        % nextPlot.
        %
        % @type rowvec<double>
        Handles;
    end
    
    properties(Access=private, Transient)
        h;
        cnt;
        ss;
    end
    
    methods
        function this = PlotManager(single, rows, cols)
            % Creates a new PlotManager
            %
            % Parameters:
            % single: If to create single figures for each call to
            % nextPlot. @type logical @default true
            % rows: If on non-single mode, the number of rows to pass to
            % subplot. @type integer
            % cols: If on non-single mode, the number of columns to pass to
            % subplot. @type integer
            if nargin > 0
                this.Single = single;
                if nargin > 1
                    this.rows = rows;
                    this.cols = cols;    
                end
            end
            this.cnt = 1;
            this.Handles = [];
            s = get(0,'ScreenSize');
            this.ss = s(3:4);
        end
        
        function h = nextPlot(this, tag)
            % Creates a new axis to plot in. Depending on the property
            % tools.PlotMananger.Single this will either advance to the
            % next subplot or open up a new figure window of size
            % SingleSize in the center of the main screen.
            %
            % If you specify a tag it will be used upon exporting created
            % plots to the file system as filename of the plot.
            %
            % Parameters:
            % tag: The tag to use for the axes. @type char @default ''
            %
            % Return values:
            % h: The handle to the new plot object. Either an axis or
            % figure handle.
            if nargin == 1
                tag = '';
            end
            this.finishCurrent;
            if this.Single
                h = figure('Position',[(this.ss - this.SingleSize)/2 this.SingleSize],'Tag',tag);
            else
                if isempty(this.h) || ~ishandle(this.h)
                    this.h = figure;
                else
                    if gcf ~= this.h
                        figure(this.h);
                    end
                end
                h = subplot(this.rows, this.cols, this.cnt, 'Tag', tag);
                this.cnt = this.cnt + 1;
            end
            this.Handles(end+1) = h;
        end
        
        function done(this)
            % Finishes the current plotting process.
            %
            % Important to call afterwards as the last plot might not get
            % finished off (currently, only "axis tight" is invoked
            % automatically)
            this.finishCurrent;
            this.cnt = 0;
        end
        
        function savePlots(this, folder, format, close)
            % Saves all plots that have been created thus far to a given
            % folder with given format.
            %
            % Parameters:
            if nargin < 4
                close = false;
                if nargin < 3
                    format = 'fig';
                    if nargin < 2
                        folder = pwd;
                    end
                end
            end
            n = length(this.Handles);
            pi = tools.ProcessIndicator(sprintf('Saving %d current plots as "%s"', n, format), n, false);
            for idx=1:n
                h = this.Handles(idx);%#ok<*PROP>
                if ishandle(h)
                    fname = get(h,'Tag');
                    % check for empty tags here as people may have changed
                    % the tag some place else in between
                    if isempty(fname)
                        fname = sprintf('plot_nr_%d',idx);
                    end
                    fname = fullfile(folder, [this.FilePrefix '_' fname]);
                    if strcmp(get(h,'Type'),'axes')
                        general.Utils.saveAxes(h, fname, format);
                    elseif strcmp(get(h,'Type'),'figure')
                        general.Utils.saveFigure(h, fname, format);
                    end
                end
                pi.step;
            end
            pi.stop;
            if close
                this.closeAll;
            end
        end
        
        function closeAll(this)
            for i=1:length(this.Handles)
                h = this.Handles(i);
                if ishandle(h) && strcmp(get(h,'Type'),'figure')
                    close(h);
                end
                if ~isempty(this.h) && ishandle(this.h)
                    close(this.h);
                end
            end
            this.Handles = [];
        end
    end
    
    methods(Access=private)
        function finishCurrent(this)
            if ~isempty(this.Handles)
                ax = this.Handles(end);
                if ishandle(ax)
                    % If not an axes, must be a figure
                    if ~strcmp(get(ax,'Type'),'axes')
                        ax = gca(ax);
                    end
                    axis(ax,'tight');
                else
                    this.Handles(end) = [];
                end
            end
        end
    end
    
end